//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class gastos
    {
        public int idGastos { get; set; }
        public int ACPM { get; set; }
        public int Aseo { get; set; }
        public int Otros { get; set; }
        public int ProducidoNeto { get; set; }
        public int SueldoConductor { get; set; }
        public int TGasto { get; set; }
        public int Turno { get; set; }
        public int PlanillaRecaudo_idPlanillaRecaudo { get; set; }
    
        public virtual planillarecaudo planillarecaudo { get; set; }
    }
}
