//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class historialmovimiento
    {
        public int idHistorialMovimiento { get; set; }
        public string Latitud { get; set; }
        public string Longitud { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> Velocidad { get; set; }
        public string Punto { get; set; }
        public string Bus_Placa { get; set; }
        public string Bus_Vial { get; set; }
    }
}
