//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class planillarecaudo
    {
        public planillarecaudo()
        {
            this.bus = new HashSet<bus>();
            this.gastos = new HashSet<gastos>();
            this.planillacontrol = new HashSet<planillacontrol>();
        }
    
        public int idPlanillaRecaudo { get; set; }
        public System.DateTime fecha { get; set; }
        public System.DateTime HoraSalida { get; set; }
        public long InicioTorniquete { get; set; }
        public long FinTorniquete { get; set; }
        public Nullable<int> NumPasajeros { get; set; }
        public Nullable<int> ProducidoBruto { get; set; }
        public string REC { get; set; }
        public string Persona_Cedula { get; set; }
    
        public virtual ICollection<bus> bus { get; set; }
        public virtual ICollection<gastos> gastos { get; set; }
        public virtual ICollection<planillacontrol> planillacontrol { get; set; }
    }
}
