//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class recorrido
    {
        public int idRecorrido { get; set; }
        public Nullable<int> Coleo { get; set; }
        public System.DateTime HEntrada { get; set; }
        public Nullable<System.DateTime> HSalida { get; set; }
        public Nullable<int> NumRecorrido { get; set; }
        public int PlanillaControl_idPlanillaControl { get; set; }
        public string TarjetaDespacho_NumTarjeta { get; set; }
    
        public virtual planillacontrol planillacontrol { get; set; }
        public virtual tarjetadespacho tarjetadespacho { get; set; }
    }
}
