//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ruta
    {
        public ruta()
        {
            this.coordenadasruta = new HashSet<coordenadasruta>();
            this.planillacontrol = new HashSet<planillacontrol>();
            this.puntoscontrol = new HashSet<puntoscontrol>();
        }
    
        public int idRuta { get; set; }
        public string Nombre { get; set; }
        public int Capacidad { get; set; }
        public string Descripcion { get; set; }
        public int Frecuencia { get; set; }
        public int Gabela { get; set; }
        public string Longitud { get; set; }
        public int TiempRecorrido { get; set; }
        public string Persona_Cedula { get; set; }
    
        public virtual ICollection<coordenadasruta> coordenadasruta { get; set; }
        public virtual ICollection<planillacontrol> planillacontrol { get; set; }
        public virtual ICollection<puntoscontrol> puntoscontrol { get; set; }
    }
}
