//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class fallasreportadas
    {
        public int idFallasReportadas { get; set; }
        public string Estado { get; set; }
        public string Falla { get; set; }
        public Nullable<System.DateTime> FchReporte { get; set; }
        public string Observaciones { get; set; }
        public string PV { get; set; }
        public string TrabajoRealizado { get; set; }
        public string Bus_Placa { get; set; }
        public string Bus_Vial { get; set; }
    }
}
