//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbtransvalleEntitie : DbContext
    {
        public dbtransvalleEntitie()
            : base("name=dbtransvalleEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bus> bus { get; set; }
        public DbSet<coordenadasruta> coordenadasruta { get; set; }
        public DbSet<documentos> documentos { get; set; }
        public DbSet<documentos_has_bus> documentos_has_bus { get; set; }
        public DbSet<fallasreportadas> fallasreportadas { get; set; }
        public DbSet<gastos> gastos { get; set; }
        public DbSet<historialmovimiento> historialmovimiento { get; set; }
        public DbSet<perfil> perfil { get; set; }
        public DbSet<persona> persona { get; set; }
        public DbSet<persona_has_documentos> persona_has_documentos { get; set; }
        public DbSet<planillacontrol> planillacontrol { get; set; }
        public DbSet<planillarecaudo> planillarecaudo { get; set; }
        public DbSet<puntoscontrol> puntoscontrol { get; set; }
        public DbSet<recorrido> recorrido { get; set; }
        public DbSet<ruta> ruta { get; set; }
        public DbSet<tallas> tallas { get; set; }
        public DbSet<tarjetadespacho> tarjetadespacho { get; set; }
        public DbSet<transvalle> transvalle { get; set; }
        public DbSet<usuario> usuario { get; set; }
    }
}
