//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public string PApellido { get; set; }
        public string SApellido { get; set; }
        public string PNombre { get; set; }
        public string SNombre { get; set; }
        public string Cedula { get; set; }
        public System.DateTime FchNac { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string EPS { get; set; }
        public string Pension { get; set; }
        public string RH { get; set; }
        public string TConductor { get; set; }
        public string Transvalle_Nit { get; set; }
        public long Usuario_idUsuario { get; set; }
    
        public virtual transvalle transvalle { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
