//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class planillacontrol
    {
        public planillacontrol()
        {
            this.bus = new HashSet<bus>();
            this.recorrido = new HashSet<recorrido>();
            this.ruta = new HashSet<ruta>();
        }
    
        public int idPlanillaControl { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Observaciones { get; set; }
        public int PlanillaRecaudo_idPlanillaRecaudo { get; set; }
        public string Persona_Cedula { get; set; }
    
        public virtual ICollection<bus> bus { get; set; }
        public virtual planillarecaudo planillarecaudo { get; set; }
        public virtual ICollection<recorrido> recorrido { get; set; }
        public virtual ICollection<ruta> ruta { get; set; }
    }
}
